<?php

namespace hnr\sircimBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{
	public function seleccionarAreasActivas()
    {
    	
         return $this->getEntityManager()
            ->createQuery('SELECT a 
                           FROM hnrsircimBundle:Area a
                           WHERE a.arEstado = 1
                           ORDER BY a.id ASC')
                ->getResult();
    }
}
