<?php

namespace hnr\sircimBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * EstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioRepository extends EntityRepository
{
	public function seleccionarEstudiosActivos()
    {
    	
         return $this->getEntityManager()
            ->createQuery('SELECT e 
                           FROM hnrsircimBundle:Estudio e
                           WHERE e.esEstado = 1
                           ORDER BY e.id ASC')
                ->getResult();
    }
}
