<?php

namespace hnr\sircimBundle\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
	public function seleccionarRolesActivos()
    {
    	
         return $this->getEntityManager()
            ->createQuery('SELECT r
                           FROM hnrsircimBundle:Rol r
                           WHERE r.arEstado = 1
                           ORDER BY r.id ASC')
                ->getResult();
    }
}
